name: Run Pipeline and Streamlit

on:
  push:
    branches: [main]

    
jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    env:
      # Todas as secrets disponíveis para todas as etapas do job
      EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install streamlit
        pip install python-dotenv

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests/

    - name: Run pipeline
      run: python src/run_pipeline.py --date $(date +%F)

    - name: Run Streamlit app
      run: streamlit run src/app.py --server.port 8501 --server.headless true
