# Este workflow é um EXEMPLO de como você faria o deploy da sua aplicação Streamlit.
# O GitHub Actions NÃO hospeda a aplicação. Ele a envia para um serviço de hospedagem.

name: Deploy Streamlit App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Checkout code
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: 3. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Deploy to a hosting service
      run: |
        echo "Esta etapa é um exemplo."
        echo "Aqui você adicionaria os comandos para fazer o deploy para um serviço como:"
        echo "- Streamlit Community Cloud (o mais recomendado)"
        echo "- Hugging Face Spaces"
        echo "- Heroku, Render, etc."
        # Exemplo (NÃO FUNCIONAL): streamlit deploy ...
